# Generated by Django 4.2.13 on 2024-05-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_branch_id_branch_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
